import "./globals.css";
import Providers from "./provider";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import NavBar from "@/components/Nav Bar/NavBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
